### ISSUE TITLE
Add support for Cypress 10

### ISSUE THREAD

**Issue by bart-krakowski** [G-Fidalgo/cypress-runner#5]
It would be great to have support for Cypress v.10
I mean test files with `cy.(j|t)s?(x)` extensions and ability to run Cypress with `--component` flag (https://docs.cypress.io/guides/component-testing/writing-your-first-component-test)

**Comment by G-Fidalgo** [comment]
Hi @bart-krakowski just gonna check if extension runs with Cypress v.10 and update it if needed, but I think that you could change the pattern of the files where to show cypress runner plugin with this setting `Code Lens Selector` I would try 
`**/*.{test,spec,cy}.{js,jsx,ts,tsx}` rather than default one :smiley:

regarding --component flag, I will add extra config setting to only add flags, but for the moment I suggest you  to try to use `Cypressrunner: Cypress Command` and you could insert the command you would like to be run with the flags 

Hope I can develop new version if needed :wink:

Thank you for taking your time to create the issue

**Comment by G-Fidalgo** [comment]
Already published new version of the plugin supporting from default *.cy.* files to show Code Lens 

Work In Progress for adding `--component` flag:
- Check that you could add custom flags on cypress run command 
- Add new code lens selector to run specific test with `--component` flag
